### ISSUE TITLE
Protect against pages which require('config.php') instead of require_once

### ISSUE THREAD

**Issue by adigitalife** [brendanheywood/moodle-local_cleanurls#23]
I've noticed 1 more issues.  It affects file resource.

File (original):  /mod/resource/view.php?id=123
File (cleaned): /course/[shortname]/resource/123-[name]

Clicking the cleaned link brings up a completely blank page.  I tried turning on debug but the log entries are pretty much the same for both working links and the non-working file links.

**Comment by brendanheywood** [comment]
Yeah this one is funky because of the different pages in moodle require config.php inconsistently. If I change the require('../config.php') in the resource modules to require_once then it works fine, but there are a whole ton of these scattered throughout moodle so I need to find a better solution. 

I think the safest option is to just not clean these types of urls and submit patches to core to change the way they include config.php

**Comment by brendanheywood** [comment]
Ok the protection is in place to not clean these. Possibly could be more performant but it works.
