### ISSUE TITLE
/mod/page/view.php urls are not rewritten

### ISSUE THREAD

**Issue by tianxang** [brendanheywood/moodle-local_cleanurls#28]
Hi,
First thank a lot for this plugin !
I add it on my website : https://www.cours-de-chinois.com
As you can see in course "Niveau 1" : https://www.cours-de-chinois.com/course/Niveau+1?section=1
url of quiz and lesson are rewrite in clean url but not page. Is that normal ?
Thanks for help !
Tianxiang

**Comment by brendanheywood** [comment]
hi @tianxang,

There are a couple of ways that different pages can be loaded in moodle which means they cannot work with this plugin, in particular for this case the view.php page uses require() instead of require_once() eg:

```
require('../../config.php');
```

If you manually change this in /mod/page/view.php and purge your caches then it should start working. I will also raise this with HQ and see if they would consider this to be part of their coding standards but this plugin it is a very fringe case so not sure. This affects many other pages too.

**Comment by tianxang** [comment]
Hi @brendanheywood !
I change require('../../config.php') to require_once('../../config.php') in /mod/page/view.php and now **it works like a charm** !
Thank you so much, your plugin is really great ! Clean Url is so important for a website. 
Best regards !
Tianxiang

**Comment by brendanheywood** [comment]
I've just found a better non-core-hack solution to this which is to change the first couple lines of config.php to:

```
<?php  // Moodle configuration file

global $CFG;
if (!isset($CFG)) {
    $CFG = new stdClass();
}

```

I've updated the README: https://github.com/brendanheywood/moodle-local_cleanurls#step-4-turn-it-on-and-configure

**Comment by tianxang** [comment]
Hi brendanheywood,
I just test it and it doesn't work for me, the 'page' url are not rewritten. I add the code to the config.php, re-change the code of  /mod/page/view.php to require('../../config.php') and clear cache but magic didn't happen.

**Comment by brendanheywood** [comment]
Did you also pull the latest version of this plugin? There was code to protect against linking to mod_page which now has been removed

**Comment by tianxang** [comment]
Hi brendanheywood,
I did not but I update it and it work perfectly now !
Thanks a lot ! You do a great job and I was looking for this feature on moodle for a long time (from moodle 2.1 when I begin...)
Do you think this plugin will be in default moodle in the future ? I can't imagine a modern website without clean url.
Best regards,
Tianxiang
