### ISSUE TITLE
Add $CFG reset in config.php test to router config page

### ISSUE THREAD

**Issue by brendanheywood** [brendanheywood/moodle-local_cleanurls#31]
To protect against the 'page' bug where because of the use of require vs require_once, the config.php is being bootstrapped a second time and the $CFG object is being reset. The root cause is the first couple lines of the default config-dist.php which can simple be changed to not reset $CFG and then it all works. This is already documented in the installation instructions but we can easily create a GUI test to make this more obvious to new admin's setting this up.

**Comment by pigletmedia** [comment]
Hi there, what is this 'page' pug?  I'm hoping its the same issue I've come up against.  Everything works, except when I try to view a course/page/etc .  At this point, it breaks (cannot find the $CFG global, thus not pulling in any of the required libraries).  Only way to fix this is by changing require('../../config.php) to require_once('../../.config.php') in mod/page/view.php.

This kind of sucks though, because we're working with many instances of Moodle and need to stay away from 'core' hacks. 

Any suggestions?

**Comment by brendanheywood** [comment]
Yes, the problem is the first few lines of config.php which resets the $CFG object, follow these steps here:

https://github.com/brendanheywood/moodle-local_cleanurls#step-4-turn-it-on-and-configure

**Comment by pigletmedia** [comment]
Aaah yes.  That seems to work thanks for the quick response.  Any reason you know why the Moodle team would "unset" the config file in the first place?

**Comment by brendanheywood** [comment]
Moodle is just being cautious, php can do magical things like insert something into the front of everything php file. So it pays to be paranoid and not assume things. In core moodle you never bootstrap a page and then bootstrap moodle again, but here we do, we load up the router.php which then figures out where it should instead be going (which needs access to all the moodle libs) and then creates a pseudo web requests and forwards to the real page which then bootstraps moodle again. There isn't a way around this - unless moodle was to move the routing logic into core which they don't seem too interested in doing.
